# Generated by Django 2.1.5 on 2019-02-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentuser', models.CharField(blank=True, max_length=50)),
                ('creator', models.CharField(blank=True, default='', max_length=50)),
                ('productname', models.CharField(blank=True, max_length=50)),
                ('productcategory', models.CharField(blank=True, max_length=50)),
                ('sessionkey', models.CharField(blank=True, max_length=50)),
                ('productimage1', models.ImageField(blank=True, upload_to='bedding/')),
                ('productimage2', models.ImageField(blank=True, upload_to='bedding/')),
                ('productimage3', models.ImageField(blank=True, upload_to='bedding/')),
                ('productimage4', models.ImageField(blank=True, upload_to='bedding/')),
                ('productimage5', models.ImageField(blank=True, upload_to='bedding/')),
                ('productimage6', models.ImageField(blank=True, upload_to='bedding/')),
                ('productadded', models.BooleanField(default=False)),
                ('orderedTime', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
