# Generated by Django 2.1.1 on 2019-02-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentuser', models.CharField(blank=True, max_length=50)),
                ('creator', models.CharField(blank=True, default='', max_length=50)),
                ('productname', models.CharField(blank=True, max_length=50)),
                ('productcategory', models.CharField(blank=True, max_length=50)),
                ('sessionkey', models.CharField(blank=True, max_length=50)),
                ('productadded', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('orderedTime', models.CharField(blank=True, max_length=50)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(blank=True, null=True, upload_to='Product_Images/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='Product_Images/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='Product_Images/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='Product_Images/')),
                ('image5', models.FileField(blank=True, null=True, upload_to='Product_Images/')),
                ('image6', models.FileField(blank=True, null=True, upload_to='Product_Images/')),
                ('productImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
