# Generated by Django 2.1.5 on 2019-02-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orderedTime',
            field=models.CharField(max_length=50),
        ),
    ]
