# Generated by Django 2.1.1 on 2019-02-25 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Name')),
                ('mobile', models.IntegerField(blank=True, null=True, verbose_name='Mobile')),
                ('streetAdrress1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address')),
                ('streetAdrress2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address 1')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('zip', models.IntegerField(blank=True, null=True, verbose_name='ZIP Code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profile_Pix/')),
                ('image2', models.ImageField(blank=True, height_field='128', null=True, upload_to='Profile_Pix/', width_field='128')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
