# Generated by Django 2.1.1 on 2019-02-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='width',
            field=models.IntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image2',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='Profile_Pix/', width_field='width'),
        ),
    ]
