# Generated by Django 2.1.5 on 2019-02-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190206_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='streetAdrress1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='streetAdrress2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='ZIP Code'),
        ),
    ]
