# Generated by Django 2.1.1 on 2019-02-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190225_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='width',
        ),
    ]
