# Generated by Django 2.1.5 on 2019-02-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190206_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepicture',
            field=models.FileField(default='background.jpg', null=True, upload_to='bedding/', verbose_name='Profile picture'),
        ),
    ]
