# Generated by Django 2.1.5 on 2019-02-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190210_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepicture',
            field=models.ImageField(default='background.jpg', null=True, upload_to='bedding/', verbose_name='Profile picture'),
        ),
    ]
